# 配布用のフォルダと ZIP を作る。
#
#   powershell -File build-deploy.ps1            web 用(公開版)
#   powershell -File build-deploy.ps1 -Local     手元用(開発版)
#   powershell -File build-deploy.ps1 -Obfuscate さらに難読化する
#   powershell -File build-deploy.ps1 -LogoTrap  ロゴを見せるために、コンソールを
#                                                開いているあいだゲームを止める
#
# -Obfuscate は terser を使う(npm i -D terser で入る)。
# 入っていなければ**エラーで止まる**(素のままの物をそのまま公開しないため)。
#
# 違いは game/build.js の dev だけ。ソースはいつも開発版なので、
# web 用のときだけ dev: false で書き換える。
#   dev: false … シーン選択・DEV 表示・画面の保存・開発用の裏技・
#                 コンソール関数(mmsxxDebug など)・BG の検査が全部消える
#   dev: true  … 手元と同じ。スマホなど localhost でない場所へ持っていっても
#                 開発用の機能が使える
#
# 注意: PowerShell の Compress-Archive は ZIP エントリ名に "\" を使うことがある。
# ZIP の仕様ではディレクトリ区切りは "/" であり、"\" のままだと展開側
# (Cloudflare Pages など) がサブフォルダと認識せず、"game\main.js" という
# 名前の 1 ファイルとして扱われて /game/main.js が 404 になる。
# そのためここでは ZipArchive でエントリ名を明示して作る。

param([switch]$Local, [switch]$Obfuscate, [switch]$LogoTrap)

$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
if ($Local) {
  $deploy = Join-Path $root 'deploy-local'
  $zipPath = Join-Path $root 'star-fable-local.zip'
} else {
  $deploy = Join-Path $root 'deploy'
  $zipPath = Join-Path $root 'star-fable-deploy.zip'
}

# 配布に必要なファイルだけをそろえる
if (Test-Path $deploy) { Remove-Item -Recurse -Force $deploy }
New-Item -ItemType Directory -Force $deploy | Out-Null
Copy-Item (Join-Path $root 'index.html') $deploy
# SNS に貼られたときの画像。**一番上に置く**(index.html と同じ高さ)
Copy-Item (Join-Path $root 'default-og-image.png') $deploy
Copy-Item -Recurse (Join-Path $root 'engine') (Join-Path $deploy 'engine')
Copy-Item -Recurse (Join-Path $root 'game') (Join-Path $deploy 'game')
# 外から持ってきた部品(bowser など)。node_modules は公開物に入れないので、
# ブラウザから読むものはここに写してある。無ければ入れない
if (Test-Path (Join-Path $root 'vendor')) {
  Copy-Item -Recurse (Join-Path $root 'vendor') (Join-Path $deploy 'vendor')
}
# サーバへ繋ぐ実装(公開しない置き場)。無ければ入れない。
# 入っていない配布物は、ランキングが手元の保存のままになるだけで遊べる
if (Test-Path (Join-Path $root 'online')) {
  Copy-Item -Recurse (Join-Path $root 'online') (Join-Path $deploy 'online')
}
# 音声ファイル(スタッフロールの mp3 など)
if (Test-Path (Join-Path $root 'assets')) {
  Copy-Item -Recurse (Join-Path $root 'assets') (Join-Path $deploy 'assets')
}
# バーチャルパッドの実験台。**開発版で実機の手触りを詰めるため**に入れる。
# 無ければ入れない
if (Test-Path (Join-Path $root 'padlab')) {
  Copy-Item -Recurse (Join-Path $root 'padlab') (Join-Path $deploy 'padlab')
}
# Cloudflare Pages の Functions と、その通り道の指定(_routes.json)。
# **_routes.json が無いと `/` は静的配信のままで Function を通らない。**
# 手元用にも入れる。**プレビュー(dev ブランチ)へ上げるときに要る**ため
if (Test-Path (Join-Path $root 'functions')) {
  Copy-Item -Recurse (Join-Path $root 'functions') (Join-Path $deploy 'functions')
  if (Test-Path (Join-Path $root '_routes.json')) {
    Copy-Item (Join-Path $root '_routes.json') $deploy
  }
}

# ビルドの種類を書き込む(元のソースには触らない)
if ($Local) { $buildName = 'local'; $devFlag = 'true' }
else        { $buildName = 'web';   $devFlag = 'false' }
if ($LogoTrap) { $trapFlag = 'true' } else { $trapFlag = 'false' }
# ビルド番号は build-number.txt に持っていて、ふだんは**ビルドするたびに 1 つ増える**。
# ゲームの版は v1.00.<ビルド番号> になる。
#
# 増えるのは**公開版(web)を作ったときだけ**。手元用(-Local)は今の番号をそのまま使う。
# 番号は「何を配ったか」を指すものなので、配らないビルドで進めない。
#
# **公開版を作るたびに 1 つ増やす。** 上げたものが最新かどうかを、
# タイトルの版で見分けられるようにするため($true にすると 0 で止まる)
$FreezeBuildNumber = $false
$numPath = Join-Path $root 'build-number.txt'
if (Test-Path $numPath) { $buildNo = [int](Get-Content $numPath -Raw).Trim() } else { $buildNo = 0 }
if ($FreezeBuildNumber) {
  $buildNo = 0
  Set-Content -Path $numPath -Value $buildNo -NoNewline -Encoding ascii
} elseif (-not $Local) {
  $buildNo++
  Set-Content -Path $numPath -Value $buildNo -NoNewline -Encoding ascii
}
# 版の頭。**ここを上げたら build-number.txt を -1 にする**と、次のビルドが .00 から始まる
$GameVersionBase = 'v1.01'
# **うしろのビルド番号が付くのは公開版だけ**。
# 手元用は版の頭だけ(v1.01)にする。どちらも頭は同じ版を名乗る
if ($Local) { $gameVersion = $GameVersionBase }
else { $gameVersion = '{0}.{1:d2}' -f $GameVersionBase, $buildNo }
# ヒアストリング(@"..."@)は改行コードが LF だけだと PowerShell 5.1 が
# 解釈に失敗するので、行の配列で組む
$buildJs = @(
  '// AUTO-GENERATED by build-deploy.ps1 - do not edit',
  'export const BUILD = {',
  "  version: '$gameVersion',",
  "  dev: $devFlag,",
  "  logoTrap: $trapFlag,",
  "  name: '$buildName',",
  '};'
) -join "`r`n"
Set-Content -Path (Join-Path $deploy 'game/build.js') -Value $buildJs -Encoding utf8

# 難読化。配布フォルダの中だけを書き換える
if ($Obfuscate) {
  # 入っていなければ**止める**。
  # 黙って素のままの物ができると、そのまま公開してしまう
  if (-not (Test-Path (Join-Path $root 'node_modules/terser'))) {
    throw '-Obfuscate には terser が要ります。npm i -D terser を実行してください'
  }
  Write-Host '難読化しています (terser)'
  & node (Join-Path $root 'tools/obfuscate.mjs') $deploy
  if ($LASTEXITCODE -ne 0) { throw '難読化に失敗しました' }
}

# ZIP を作り直す (エントリ名は必ず "/" 区切り)
Add-Type -AssemblyName System.IO.Compression
Add-Type -AssemblyName System.IO.Compression.FileSystem
if (Test-Path $zipPath) { Remove-Item -Force $zipPath }
$zip = [System.IO.Compression.ZipFile]::Open($zipPath, 'Create')
try {
  Get-ChildItem -Recurse -File $deploy | ForEach-Object {
    $name = $_.FullName.Substring($deploy.Length + 1).Replace('\', '/')
    [void][System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile($zip, $_.FullName, $name)
  }
} finally {
  $zip.Dispose()
}

# 確認のためエントリ名を表示する
$check = [System.IO.Compression.ZipFile]::OpenRead($zipPath)
$check.Entries | ForEach-Object { $_.FullName }
$check.Dispose()
"{0} ビルド {1}: {2}" -f $buildName, $gameVersion, (Split-Path -Leaf $zipPath)
"{0:N0} bytes" -f (Get-Item $zipPath).Length
